//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffaireCommerciales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AffaireCommerciales()
        {
            this.DEVIS_CLIENTS = new HashSet<DEVIS_CLIENTS>();
            this.PROJET_TECHNIQUE = new HashSet<PROJET_TECHNIQUE>();
        }
    
        public int AffaireCommercialeId { get; set; }
        public string Reference { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public string EtatSoum { get; set; }
        public Nullable<float> Cout { get; set; }
        public int ClientId { get; set; }
        public int PersonnelId { get; set; }
        public string EnCourExecution { get; set; }
        public Nullable<int> Importance { get; set; }
        public Nullable<int> NbHeurePrepOffre { get; set; }
        public string faisabilite { get; set; }
        public Nullable<System.DateTime> DateConsultation { get; set; }
        public string AffaireObtenue { get; set; }
        public Nullable<int> ResponsableTechnique { get; set; }
        public Nullable<int> CoordinateurCommerciale { get; set; }
        public Nullable<int> CoordinateurRealisation { get; set; }
        public Nullable<System.DateTime> DateLivraison { get; set; }
        public Nullable<System.DateTime> Delai_de_Soumission { get; set; }
        public Nullable<System.DateTime> Date_de_Soumission { get; set; }
    
        public virtual Personnels Personnels { get; set; }
        public virtual Personnels Personnels1 { get; set; }
        public virtual Personnels Personnels2 { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual Personnels Personnels3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVIS_CLIENTS> DEVIS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJET_TECHNIQUE> PROJET_TECHNIQUE { get; set; }
    }
}
