//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art_Depot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art_Depot()
        {
            this.Art_Depot_Rayon = new HashSet<Art_Depot_Rayon>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Art { get; set; }
        public Nullable<int> Id_Dépot { get; set; }
        public Nullable<decimal> Stock_Art_Dépot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Art_Depot_Rayon> Art_Depot_Rayon { get; set; }
        public virtual Prix_Achat Prix_Achat { get; set; }
        public virtual Dépot Dépot { get; set; }
    }
}
