//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art_Depot_Rayon
    {
        public int Id { get; set; }
        public Nullable<int> Id_Art_Depot { get; set; }
        public Nullable<int> Id_Rayons { get; set; }
        public Nullable<decimal> Stock_Rayon { get; set; }
    
        public virtual Art_Depot Art_Depot { get; set; }
        public virtual Rayons Rayons { get; set; }
    }
}
