//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVOIRS_FOURNISSEURS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AVOIRS_FOURNISSEURS()
        {
            this.LIGNES_AVOIRS_FOURNISSEURS = new HashSet<LIGNES_AVOIRS_FOURNISSEURS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int FOURNISSEUR { get; set; }
        public int Societes { get; set; }
        public Nullable<decimal> THT { get; set; }
        public Nullable<decimal> TTVA { get; set; }
        public Nullable<decimal> NHT { get; set; }
        public decimal TTC { get; set; }
        public Nullable<decimal> TNET { get; set; }
        public bool VALIDER { get; set; }
        public Nullable<int> FACTURE_FOURNISSEUR { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public Nullable<int> Tiers { get; set; }
        public Nullable<bool> Declaration { get; set; }
        public Nullable<System.DateTime> Date_Declaration { get; set; }
        public Nullable<decimal> TIMBRE { get; set; }
        public string Designation { get; set; }
    
        public virtual FACTURES_FOURNISSEURS FACTURES_FOURNISSEURS { get; set; }
        public virtual FOURNISSEURS FOURNISSEURS { get; set; }
        public virtual Societes Societes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_AVOIRS_FOURNISSEURS> LIGNES_AVOIRS_FOURNISSEURS { get; set; }
    }
}
