//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONS_LIVRAISONS_PART_CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BONS_LIVRAISONS_PART_CLIENTS()
        {
            this.LIGNES_BONS_LIVRAISONS_PART_CLIENTS = new HashSet<LIGNES_BONS_LIVRAISONS_PART_CLIENTS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public Nullable<int> IDBLC { get; set; }
        public Nullable<int> Code_Article { get; set; }
        public string DESIGNATION_PRODUIT { get; set; }
        public Nullable<double> QTELIV { get; set; }
        public Nullable<double> QTERES { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<bool> Etat { get; set; }
        public Nullable<bool> VALIDER { get; set; }
    
        public virtual BONS_LIVRAISONS_CLIENTS BONS_LIVRAISONS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_BONS_LIVRAISONS_PART_CLIENTS> LIGNES_BONS_LIVRAISONS_PART_CLIENTS { get; set; }
    }
}
