//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGETS
    {
        public int ID { get; set; }
        public decimal MONTANT_HT { get; set; }
        public Nullable<int> PROJET { get; set; }
        public Nullable<int> CENTRE_COUT { get; set; }
        public Nullable<int> SOCIETE { get; set; }
    }
}
