//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAISSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAISSON()
        {
            this.DESCRIPTION_CAISSON = new HashSet<DESCRIPTION_CAISSON>();
            this.LIGNES_CUISINE_BONLIVRAISON_CLIENTS = new HashSet<LIGNES_CUISINE_BONLIVRAISON_CLIENTS>();
            this.LIGNES_CUISINE_CAISSE_CLIENTS = new HashSet<LIGNES_CUISINE_CAISSE_CLIENTS>();
            this.LIGNES_CUISINE_COMMANDE_CLIENTS = new HashSet<LIGNES_CUISINE_COMMANDE_CLIENTS>();
            this.LIGNES_CUISINE_DEVIS_CLIENTS = new HashSet<LIGNES_CUISINE_DEVIS_CLIENTS>();
            this.LIGNES_CUISINE_FACTURE_CLIENTS = new HashSet<LIGNES_CUISINE_FACTURE_CLIENTS>();
            this.LIGNES_CUISINE_FACTURE_CLIENTS1 = new HashSet<LIGNES_CUISINE_FACTURE_CLIENTS>();
            this.LIGNES_CUISINE_CAISSE_CLIENTS1 = new HashSet<LIGNES_CUISINE_CAISSE_CLIENTS>();
            this.LIGNES_CUISINE_AVOIR_CLIENTS = new HashSet<LIGNES_CUISINE_AVOIR_CLIENTS>();
        }
    
        public int ID { get; set; }
        public string REF_BAS { get; set; }
        public Nullable<int> ID_ACC { get; set; }
        public Nullable<int> ID_FAC { get; set; }
        public Nullable<decimal> PTHT { get; set; }
        public Nullable<decimal> PTTC { get; set; }
        public Nullable<int> TYPE_CAISSON { get; set; }
        public Nullable<int> CATEGORIE { get; set; }
        public Nullable<decimal> TOTSURFACE { get; set; }
    
        public virtual ACCESSOIRE ACCESSOIRE { get; set; }
        public virtual Categorie Categorie1 { get; set; }
        public virtual TYPE_CAISSON TYPE_CAISSON1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESCRIPTION_CAISSON> DESCRIPTION_CAISSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_BONLIVRAISON_CLIENTS> LIGNES_CUISINE_BONLIVRAISON_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_CAISSE_CLIENTS> LIGNES_CUISINE_CAISSE_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_COMMANDE_CLIENTS> LIGNES_CUISINE_COMMANDE_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_DEVIS_CLIENTS> LIGNES_CUISINE_DEVIS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_FACTURE_CLIENTS> LIGNES_CUISINE_FACTURE_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_FACTURE_CLIENTS> LIGNES_CUISINE_FACTURE_CLIENTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_CAISSE_CLIENTS> LIGNES_CUISINE_CAISSE_CLIENTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_AVOIR_CLIENTS> LIGNES_CUISINE_AVOIR_CLIENTS { get; set; }
    }
}
