//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAISSON_HAUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAISSON_HAUT()
        {
            this.DESCRIPTION_CAISSON_HAUT = new HashSet<DESCRIPTION_CAISSON_HAUT>();
        }
    
        public int ID { get; set; }
        public string REF_HAUT { get; set; }
        public Nullable<int> ID_ACC { get; set; }
        public Nullable<int> ID_FAC { get; set; }
        public Nullable<decimal> PTHT { get; set; }
        public Nullable<decimal> PTTC { get; set; }
    
        public virtual ACCESSOIRE ACCESSOIRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESCRIPTION_CAISSON_HAUT> DESCRIPTION_CAISSON_HAUT { get; set; }
    }
}
