//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE_FOURNISSEUR
    {
        public int ID { get; set; }
        public string NumCheque { get; set; }
        public Nullable<int> Fournisseur { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public Nullable<System.DateTime> DateCheque { get; set; }
        public Nullable<System.DateTime> DatePayement { get; set; }
        public string Status { get; set; }
    
        public virtual FOURNISSEURS FOURNISSEURS { get; set; }
    }
}
