//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTS()
        {
            this.AffaireCommerciales = new HashSet<AffaireCommerciales>();
            this.AVOIRS_CLIENTS = new HashSet<AVOIRS_CLIENTS>();
            this.BONS_LIVRAISONS_CLIENTS = new HashSet<BONS_LIVRAISONS_CLIENTS>();
            this.Caisse = new HashSet<Caisse>();
            this.CHEQUE_CLIENT = new HashSet<CHEQUE_CLIENT>();
            this.COMMANDES_CLIENTS = new HashSet<COMMANDES_CLIENTS>();
            this.PROJET_TECHNIQUE = new HashSet<PROJET_TECHNIQUE>();
            this.DEVIS_CLIENTS = new HashSet<DEVIS_CLIENTS>();
            this.FACTURES_CLIENTS = new HashSet<FACTURES_CLIENTS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NOM { get; set; }
        public string ADRESSE { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string SITE_WEB { get; set; }
        public string ID_FISCAL { get; set; }
        public string AI { get; set; }
        public string NIS { get; set; }
        public string RC { get; set; }
        public string RIB { get; set; }
        public string CONTACT { get; set; }
        public bool Exttva { get; set; }
        public Nullable<int> Societe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffaireCommerciales> AffaireCommerciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVOIRS_CLIENTS> AVOIRS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONS_LIVRAISONS_CLIENTS> BONS_LIVRAISONS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caisse> Caisse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHEQUE_CLIENT> CHEQUE_CLIENT { get; set; }
        public virtual SocieteLogo SocieteLogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDES_CLIENTS> COMMANDES_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJET_TECHNIQUE> PROJET_TECHNIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVIS_CLIENTS> DEVIS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURES_CLIENTS> FACTURES_CLIENTS { get; set; }
    }
}
