//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients1
    {
        public int ClientId { get; set; }
        public string Nom { get; set; }
        public string Responsable { get; set; }
        public string Adresse { get; set; }
        public long TelePhone { get; set; }
        public long TelFix { get; set; }
        public string Email { get; set; }
    }
}
