//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decaissement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Decaissement()
        {
            this.Commande = new HashSet<Commande>();
            this.Projets1 = new HashSet<Projets>();
        }
    
        public int DecaissID { get; set; }
        public Nullable<int> CentreID { get; set; }
        public Nullable<int> DiretionID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> qte { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<int> CatID { get; set; }
        public string Mo_pay { get; set; }
        public string Demandeur { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<int> PrID { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commande { get; set; }
        public virtual Sous_Categorie Sous_Categorie { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Projets Projets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projets> Projets1 { get; set; }
    }
}
