//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCRIPTION_CAISSON_COLONNE
    {
        public int ID { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> LONGE { get; set; }
        public Nullable<decimal> LARGE { get; set; }
        public Nullable<decimal> EP { get; set; }
        public Nullable<decimal> CHUTTE { get; set; }
        public Nullable<decimal> SURFACE { get; set; }
        public Nullable<decimal> QUANTITE { get; set; }
        public Nullable<decimal> PUHT { get; set; }
        public Nullable<decimal> PTHT { get; set; }
        public Nullable<decimal> PTTC { get; set; }
        public Nullable<decimal> TVA { get; set; }
        public Nullable<int> ID_CAISS_COLONNE { get; set; }
    
        public virtual CAISSON_COLONNE CAISSON_COLONNE { get; set; }
    }
}
