//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVIS_CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVIS_CLIENTS()
        {
            this.Caisse = new HashSet<Caisse>();
            this.COMMANDES_CLIENTS = new HashSet<COMMANDES_CLIENTS>();
            this.FACTURES_CLIENTS = new HashSet<FACTURES_CLIENTS>();
            this.LIGNES_CUISINE_DEVIS_CLIENTS = new HashSet<LIGNES_CUISINE_DEVIS_CLIENTS>();
            this.LIGNES_DEVIS_CLIENTS = new HashSet<LIGNES_DEVIS_CLIENTS>();
            this.lIGNES_SERVICES = new HashSet<lIGNES_SERVICES>();
            this.lIGNES_SERVICESSSTRAITANCE = new HashSet<lIGNES_SERVICESSSTRAITANCE>();
        }
    
        public int ID { get; set; }
        public string Designation { get; set; }
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int CLIENT { get; set; }
        public Nullable<decimal> THT { get; set; }
        public Nullable<decimal> TTVA { get; set; }
        public Nullable<decimal> NHT { get; set; }
        public decimal TTC { get; set; }
        public Nullable<decimal> TNET { get; set; }
        public Nullable<bool> VALIDER { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public int Societes { get; set; }
        public Nullable<int> Tiers { get; set; }
        public Nullable<bool> convert { get; set; }
        public Nullable<decimal> TVAInstallation { get; set; }
        public Nullable<decimal> Marge { get; set; }
        public Nullable<int> Id_AffaireCommerciale { get; set; }
        public string ConditionPaiement { get; set; }
        public string FINTION { get; set; }
        public string Tiroirs { get; set; }
        public string Charnieres { get; set; }
    
        public virtual AffaireCommerciales AffaireCommerciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caisse> Caisse { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDES_CLIENTS> COMMANDES_CLIENTS { get; set; }
        public virtual DEVIS_CLIENTS DEVIS_CLIENTS1 { get; set; }
        public virtual DEVIS_CLIENTS DEVIS_CLIENTS2 { get; set; }
        public virtual DEVIS_CLIENTS DEVIS_CLIENTS11 { get; set; }
        public virtual DEVIS_CLIENTS DEVIS_CLIENTS3 { get; set; }
        public virtual SocieteLogo SocieteLogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURES_CLIENTS> FACTURES_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_DEVIS_CLIENTS> LIGNES_CUISINE_DEVIS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_DEVIS_CLIENTS> LIGNES_DEVIS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICES> lIGNES_SERVICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICESSSTRAITANCE> lIGNES_SERVICESSSTRAITANCE { get; set; }
    }
}
