//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVIS_FOURNISSEURS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVIS_FOURNISSEURS()
        {
            this.COMMANDES_FOURNISSEURS = new HashSet<COMMANDES_FOURNISSEURS>();
            this.LIGNES_DEVIS_FOURNISSEURS = new HashSet<LIGNES_DEVIS_FOURNISSEURS>();
            this.lIGNE_SERVICE_FOURNISSEUR = new HashSet<lIGNE_SERVICE_FOURNISSEUR>();
        }
    
        public int ID { get; set; }
        public string Designation { get; set; }
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int FOURNISSEUR { get; set; }
        public Nullable<decimal> THT { get; set; }
        public Nullable<decimal> TTVA { get; set; }
        public Nullable<decimal> NHT { get; set; }
        public Nullable<decimal> TTC { get; set; }
        public Nullable<decimal> TNET { get; set; }
        public Nullable<bool> VALIDER { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public int Societes { get; set; }
        public Nullable<int> Tiers { get; set; }
        public Nullable<bool> convert { get; set; }
        public Nullable<System.DateTime> Validite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDES_FOURNISSEURS> COMMANDES_FOURNISSEURS { get; set; }
        public virtual SocieteLogo SocieteLogo { get; set; }
        public virtual FOURNISSEURS FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_DEVIS_FOURNISSEURS> LIGNES_DEVIS_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNE_SERVICE_FOURNISSEUR> lIGNE_SERVICE_FOURNISSEUR { get; set; }
    }
}
