//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direction()
        {
            this.Decaissement = new HashSet<Decaissement>();
        }
    
        public int DiretionID { get; set; }
        public string Nom { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> Année { get; set; }
        public Nullable<int> SCoorID { get; set; }
        public Nullable<int> SociID { get; set; }
        public Nullable<int> SocilogoID { get; set; }
    
        public virtual CoordonneesSoc CoordonneesSoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decaissement> Decaissement { get; set; }
        public virtual Direction Direction1 { get; set; }
        public virtual Direction Direction2 { get; set; }
        public virtual SocieteLogo SocieteLogo { get; set; }
        public virtual Societes Societes { get; set; }
    }
}
