//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int DocumentId { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public string UrlDoc { get; set; }
        public string Etat { get; set; }
        public string Type { get; set; }
        public System.DateTime DateEdition { get; set; }
        public int TacheId { get; set; }
    }
}
