//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Détails_Articles
    {
        public int ID { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Quantite { get; set; }
        public Nullable<int> NumBl { get; set; }
        public Nullable<int> IdPrixAchat { get; set; }
        public Nullable<int> Fournisseur { get; set; }
        public Nullable<int> NumFact { get; set; }
    
        public virtual Prix_Achat Prix_Achat { get; set; }
    }
}
