//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURES_FOURNISSEURS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURES_FOURNISSEURS()
        {
            this.AVOIRS_FOURNISSEURS = new HashSet<AVOIRS_FOURNISSEURS>();
            this.LIGNES_FACTURES_FOURNISSEURS = new HashSet<LIGNES_FACTURES_FOURNISSEURS>();
            this.RETENUE_S_FOURNISSEURS1 = new HashSet<RETENUE_S_FOURNISSEURS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int FOURNISSEUR { get; set; }
        public Nullable<int> Societes { get; set; }
        public Nullable<decimal> THT { get; set; }
        public Nullable<decimal> TTVA { get; set; }
        public Nullable<decimal> NHT { get; set; }
        public decimal TTC { get; set; }
        public Nullable<decimal> TNET { get; set; }
        public bool VALIDER { get; set; }
        public bool PAYEE { get; set; }
        public Nullable<int> COMMANDE_FOURNISSEUR { get; set; }
        public Nullable<int> BON_RECEPTION_FOURNISSEUR { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public Nullable<decimal> TIMBRE { get; set; }
        public Nullable<int> Tiers { get; set; }
        public Nullable<decimal> FODEC { get; set; }
        public Nullable<decimal> Redevance { get; set; }
        public string Num_Fact { get; set; }
        public Nullable<bool> Declaration { get; set; }
        public Nullable<System.DateTime> Date_Declaration { get; set; }
        public Nullable<bool> immobilisation { get; set; }
        public Nullable<bool> Bien_service { get; set; }
        public Nullable<bool> RAS_Marche { get; set; }
        public string MOIS_RAS_Marche { get; set; }
        public string Designation { get; set; }
        public Nullable<int> ID_RETENUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVOIRS_FOURNISSEURS> AVOIRS_FOURNISSEURS { get; set; }
        public virtual BONS_RECEPTIONS_FOURNISSEURS BONS_RECEPTIONS_FOURNISSEURS { get; set; }
        public virtual COMMANDES_FOURNISSEURS COMMANDES_FOURNISSEURS { get; set; }
        public virtual FOURNISSEURS FOURNISSEURS { get; set; }
        public virtual RETENUE_S_FOURNISSEURS RETENUE_S_FOURNISSEURS { get; set; }
        public virtual SocieteLogo SocieteLogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_FACTURES_FOURNISSEURS> LIGNES_FACTURES_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETENUE_S_FOURNISSEURS> RETENUE_S_FOURNISSEURS1 { get; set; }
    }
}
