//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURES_CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURES_CLIENTS()
        {
            this.AVOIRS_CLIENTS = new HashSet<AVOIRS_CLIENTS>();
            this.LIGNES_CUISINE_FACTURE_CLIENTS = new HashSet<LIGNES_CUISINE_FACTURE_CLIENTS>();
            this.LIGNES_FACTURES_CLIENTS = new HashSet<LIGNES_FACTURES_CLIENTS>();
            this.lIGNES_SERVICES_FACTURES = new HashSet<lIGNES_SERVICES_FACTURES>();
            this.lIGNES_SERVICESSSTRAITANCE_FACTURE = new HashSet<lIGNES_SERVICESSSTRAITANCE_FACTURE>();
        }
    
        public int ID { get; set; }
        public string Designation { get; set; }
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int CLIENT { get; set; }
        public Nullable<decimal> THT { get; set; }
        public Nullable<decimal> TTVA { get; set; }
        public Nullable<decimal> NHT { get; set; }
        public decimal TTC { get; set; }
        public Nullable<decimal> TNET { get; set; }
        public bool VALIDER { get; set; }
        public Nullable<int> COMMANDE_CLIENT { get; set; }
        public Nullable<int> DEVIS_CLIENT { get; set; }
        public Nullable<int> BON_LIVRAISON_CLIENT { get; set; }
        public Nullable<bool> PAYEE { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public Nullable<decimal> TIMBRE { get; set; }
        public Nullable<int> Societes { get; set; }
        public Nullable<int> Tiers { get; set; }
        public Nullable<bool> Declaration { get; set; }
        public Nullable<System.DateTime> Date_Declaration { get; set; }
        public Nullable<bool> immobilisation { get; set; }
        public Nullable<bool> Bien_service { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVOIRS_CLIENTS> AVOIRS_CLIENTS { get; set; }
        public virtual BONS_LIVRAISONS_CLIENTS BONS_LIVRAISONS_CLIENTS { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual COMMANDES_CLIENTS COMMANDES_CLIENTS { get; set; }
        public virtual DEVIS_CLIENTS DEVIS_CLIENTS { get; set; }
        public virtual SocieteLogo SocieteLogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_FACTURE_CLIENTS> LIGNES_CUISINE_FACTURE_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_FACTURES_CLIENTS> LIGNES_FACTURES_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICES_FACTURES> lIGNES_SERVICES_FACTURES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICESSSTRAITANCE_FACTURE> lIGNES_SERVICESSSTRAITANCE_FACTURE { get; set; }
    }
}
