//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOPROLOS
    {
        public Nullable<decimal> FOPROLOS1 { get; set; }
        public Nullable<decimal> FOPROLOS11 { get; set; }
        public string Date { get; set; }
        public int id { get; set; }
    }
}
