//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOURNISSEURS_TIERS
    {
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public int ID { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> FOURNISSEUR { get; set; }
        public Nullable<int> REF { get; set; }
    }
}
