//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIGNES_COMMANDES_FOURNISSEURS
    {
        public int ID { get; set; }
        public string DESIGNATION_PRODUIT { get; set; }
        public Nullable<double> QUANTITE { get; set; }
        public Nullable<decimal> PRIX_UNITAIRE_HT { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public Nullable<decimal> TOTALE_REMISE_HT { get; set; }
        public Nullable<decimal> TOTALE_HT { get; set; }
        public Nullable<int> TVA { get; set; }
        public Nullable<decimal> TOTALE_TTC { get; set; }
        public Nullable<int> COMMANDE_FOURNISSEUR { get; set; }
        public string Categorie { get; set; }
        public string Sous_Categorie { get; set; }
        public string Marque { get; set; }
        public string Unite { get; set; }
        public string Devise { get; set; }
        public Nullable<System.DateTime> Date_offre_de_prix { get; set; }
        public Nullable<int> Duree_de_validite { get; set; }
        public string N_Offre_de_Prix { get; set; }
        public string Libelle_Prd { get; set; }
        public Nullable<int> Prix_achat { get; set; }
    
        public virtual COMMANDES_FOURNISSEURS COMMANDES_FOURNISSEURS { get; set; }
        public virtual LIGNES_COMMANDES_FOURNISSEURS LIGNES_COMMANDES_FOURNISSEURS1 { get; set; }
        public virtual LIGNES_COMMANDES_FOURNISSEURS LIGNES_COMMANDES_FOURNISSEURS2 { get; set; }
    }
}
