//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lIGNES_SERVICES_FACTURES
    {
        public int ID { get; set; }
        public Nullable<decimal> QUANTITE { get; set; }
        public Nullable<decimal> PRIX_UNITAIRE_HT { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public Nullable<decimal> TOTALE_REMISE_HT { get; set; }
        public Nullable<decimal> TOTALE_HT { get; set; }
        public Nullable<int> TVA { get; set; }
        public Nullable<decimal> TOTALE_TTC { get; set; }
        public Nullable<int> FACTURE_CLIENT { get; set; }
        public Nullable<int> SERVICES { get; set; }
        public Nullable<int> Personnels { get; set; }
        public string Unite { get; set; }
        public string Devise { get; set; }
        public Nullable<System.DateTime> Date_offre_de_prix { get; set; }
        public Nullable<int> Duree_de_validite { get; set; }
        public Nullable<decimal> MARGE { get; set; }
        public Nullable<decimal> PRIX_UNITAIRE_HTVente { get; set; }
    
        public virtual FACTURES_CLIENTS FACTURES_CLIENTS { get; set; }
        public virtual Personnels Personnels1 { get; set; }
        public virtual SERVICES SERVICES1 { get; set; }
    }
}
