//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIGNES_CUISINE_CAISSE_CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIGNES_CUISINE_CAISSE_CLIENTS()
        {
            this.LIGNES_DESCRIPTION_ACCESOIRE_CAISSE = new HashSet<LIGNES_DESCRIPTION_ACCESOIRE_CAISSE>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> QuantiteCAISSON { get; set; }
        public Nullable<int> SSCAISSON { get; set; }
        public Nullable<decimal> CREVCAISSON { get; set; }
        public Nullable<decimal> MARGEPRIXACHAT { get; set; }
        public Nullable<decimal> PRIXACHAT { get; set; }
        public Nullable<decimal> ACC { get; set; }
        public Nullable<decimal> POURCENTAGE { get; set; }
        public Nullable<decimal> PRIXVENTECAISSON { get; set; }
        public Nullable<int> SOUSFACADE { get; set; }
        public Nullable<decimal> QuantiteFACADE { get; set; }
        public Nullable<decimal> PRIXFACADE { get; set; }
        public Nullable<decimal> PTHTFACADE { get; set; }
        public Nullable<decimal> PTHTSSMARGE { get; set; }
        public Nullable<decimal> PTHTAVECMARGE { get; set; }
        public Nullable<int> CAISSE { get; set; }
        public Nullable<int> TVACUISINE { get; set; }
        public Nullable<decimal> PTTCCUISINE { get; set; }
        public Nullable<int> TYPECAISSON { get; set; }
        public Nullable<int> TYPEFACADE { get; set; }
    
        public virtual Caisse Caisse1 { get; set; }
        public virtual CAISSON CAISSON { get; set; }
        public virtual Prix_Achat Prix_Achat { get; set; }
        public virtual SS_FACADE SS_FACADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_DESCRIPTION_ACCESOIRE_CAISSE> LIGNES_DESCRIPTION_ACCESOIRE_CAISSE { get; set; }
        public virtual CAISSON CAISSON1 { get; set; }
    }
}
