//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lIGNE_SERVICE_FOURNISSEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lIGNE_SERVICE_FOURNISSEUR()
        {
            this.lIGNE_SERVICE_FOURNISSEUR1 = new HashSet<lIGNE_SERVICE_FOURNISSEUR>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> QUANTITE { get; set; }
        public Nullable<decimal> PRIX_UNITAIRE_HT { get; set; }
        public Nullable<decimal> REMISE { get; set; }
        public Nullable<decimal> TOTALE_REMISE_HT { get; set; }
        public Nullable<decimal> TOTALE_HT { get; set; }
        public Nullable<int> TVA { get; set; }
        public Nullable<decimal> TOTALE_TTC { get; set; }
        public Nullable<int> DEVIS_FOURNISSEURS { get; set; }
        public Nullable<int> SERVICES { get; set; }
        public Nullable<int> Personnels { get; set; }
        public string Unite { get; set; }
        public string Devise { get; set; }
        public Nullable<System.DateTime> Date_offre_de_prix { get; set; }
        public Nullable<int> Duree_de_validite { get; set; }
        public Nullable<decimal> MARGE { get; set; }
        public Nullable<decimal> PRIX_UNITAIRE_HTVente { get; set; }
        public Nullable<int> DEVISFOURNISSEURS { get; set; }
        public string REFSERVICE { get; set; }
        public string DescriptionSERVICE { get; set; }
        public Nullable<int> BON_RECEPTION_FOURNISSEUR { get; set; }
        public Nullable<int> COMMANDE_FOURNISSEUR { get; set; }
        public Nullable<int> FACTURE_FOURNISSEUR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNE_SERVICE_FOURNISSEUR> lIGNE_SERVICE_FOURNISSEUR1 { get; set; }
        public virtual lIGNE_SERVICE_FOURNISSEUR lIGNE_SERVICE_FOURNISSEUR2 { get; set; }
        public virtual DEVIS_FOURNISSEURS DEVIS_FOURNISSEURS1 { get; set; }
    }
}
