//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MED_TRABELSI : DbContext
    {
        public MED_TRABELSI()
            : base("name=MED_TRABELSI")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ACCESSOIRE> ACCESSOIRE { get; set; }
        public virtual DbSet<ACHATS_PREVISIONNELS> ACHATS_PREVISIONNELS { get; set; }
        public virtual DbSet<AffaireCommerciales> AffaireCommerciales { get; set; }
        public virtual DbSet<Art_Depot> Art_Depot { get; set; }
        public virtual DbSet<Art_Depot_Rayon> Art_Depot_Rayon { get; set; }
        public virtual DbSet<AVOIRS_CLIENTS> AVOIRS_CLIENTS { get; set; }
        public virtual DbSet<AVOIRS_FOURNISSEURS> AVOIRS_FOURNISSEURS { get; set; }
        public virtual DbSet<BONS_LIVRAISONS_CLIENTS> BONS_LIVRAISONS_CLIENTS { get; set; }
        public virtual DbSet<BONS_LIVRAISONS_PART_CLIENTS> BONS_LIVRAISONS_PART_CLIENTS { get; set; }
        public virtual DbSet<BONS_RECEPTIONS_FOURNISSEURS> BONS_RECEPTIONS_FOURNISSEURS { get; set; }
        public virtual DbSet<Caisse> Caisse { get; set; }
        public virtual DbSet<CAISSON> CAISSON { get; set; }
        public virtual DbSet<CAISSON_COLONNE> CAISSON_COLONNE { get; set; }
        public virtual DbSet<CAISSON_HAUT> CAISSON_HAUT { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CATEGORIE_SUPERIEUR> CATEGORIE_SUPERIEUR { get; set; }
        public virtual DbSet<CHEQUE_CLIENT> CHEQUE_CLIENT { get; set; }
        public virtual DbSet<CHEQUE_FOURNISSEUR> CHEQUE_FOURNISSEUR { get; set; }
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<Clients1> Clients1 { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<COMMANDES_CLIENTS> COMMANDES_CLIENTS { get; set; }
        public virtual DbSet<COMMANDES_FOURNISSEURS> COMMANDES_FOURNISSEURS { get; set; }
        public virtual DbSet<CoordonneesSoc> CoordonneesSoc { get; set; }
        public virtual DbSet<Decaissement> Decaissement { get; set; }
        public virtual DbSet<DeclarationTVA> DeclarationTVA { get; set; }
        public virtual DbSet<Dépot> Dépot { get; set; }
        public virtual DbSet<DESCRIPTION_ACCESOIRE> DESCRIPTION_ACCESOIRE { get; set; }
        public virtual DbSet<DESCRIPTION_CAISSON> DESCRIPTION_CAISSON { get; set; }
        public virtual DbSet<DESCRIPTION_CAISSON_COLONNE> DESCRIPTION_CAISSON_COLONNE { get; set; }
        public virtual DbSet<DESCRIPTION_CAISSON_HAUT> DESCRIPTION_CAISSON_HAUT { get; set; }
        public virtual DbSet<DESCRIPTION_FAC_LAQUE> DESCRIPTION_FAC_LAQUE { get; set; }
        public virtual DbSet<DESCRIPTION_FAC_PLAQ> DESCRIPTION_FAC_PLAQ { get; set; }
        public virtual DbSet<DESCRIPTION_FAC_PVC> DESCRIPTION_FAC_PVC { get; set; }
        public virtual DbSet<DESCRIPTION_SOUSCATEGORIE> DESCRIPTION_SOUSCATEGORIE { get; set; }
        public virtual DbSet<DESCRIPTION_SSFAC> DESCRIPTION_SSFAC { get; set; }
        public virtual DbSet<Détails_Articles> Détails_Articles { get; set; }
        public virtual DbSet<DEVIS_CLIENTS> DEVIS_CLIENTS { get; set; }
        public virtual DbSet<DEVIS_FOURNISSEURS> DEVIS_FOURNISSEURS { get; set; }
        public virtual DbSet<Devise> Devise { get; set; }
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<DROIT_ACCES> DROIT_ACCES { get; set; }
        public virtual DbSet<Encaissement> Encaissement { get; set; }
        public virtual DbSet<Exercice> Exercice { get; set; }
        public virtual DbSet<FACADE> FACADE { get; set; }
        public virtual DbSet<FACADE__LAQUE> FACADE__LAQUE { get; set; }
        public virtual DbSet<FACADE_PLAQ> FACADE_PLAQ { get; set; }
        public virtual DbSet<FACADE_PVC> FACADE_PVC { get; set; }
        public virtual DbSet<Facturation> Facturation { get; set; }
        public virtual DbSet<FACTURES_CLIENTS> FACTURES_CLIENTS { get; set; }
        public virtual DbSet<FACTURES_FOURNISSEURS> FACTURES_FOURNISSEURS { get; set; }
        public virtual DbSet<FAMILLES_PRODUITS> FAMILLES_PRODUITS { get; set; }
        public virtual DbSet<FOPROLOS> FOPROLOS { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<FOURNISSEURS> FOURNISSEURS { get; set; }
        public virtual DbSet<Horaire> Horaire { get; set; }
        public virtual DbSet<horaire_jour> horaire_jour { get; set; }
        public virtual DbSet<Inscription> Inscription { get; set; }
        public virtual DbSet<Jours> Jours { get; set; }
        public virtual DbSet<LIGNES_AVOIRS_CLIENTS> LIGNES_AVOIRS_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_AVOIRS_FOURNISSEURS> LIGNES_AVOIRS_FOURNISSEURS { get; set; }
        public virtual DbSet<LIGNES_BONS_LIVRAISONS_CLIENTS> LIGNES_BONS_LIVRAISONS_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_BONS_LIVRAISONS_PART_CLIENTS> LIGNES_BONS_LIVRAISONS_PART_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_BONS_RECEPTIONS_FOURNISSEURS> LIGNES_BONS_RECEPTIONS_FOURNISSEURS { get; set; }
        public virtual DbSet<LIGNES_Caisse> LIGNES_Caisse { get; set; }
        public virtual DbSet<LIGNES_COMMANDES_CLIENTS> LIGNES_COMMANDES_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_COMMANDES_FOURNISSEURS> LIGNES_COMMANDES_FOURNISSEURS { get; set; }
        public virtual DbSet<LIGNES_CUISINE_BONLIVRAISON_CLIENTS> LIGNES_CUISINE_BONLIVRAISON_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_CUISINE_CAISSE_CLIENTS> LIGNES_CUISINE_CAISSE_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_CUISINE_COMMANDE_CLIENTS> LIGNES_CUISINE_COMMANDE_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_CUISINE_DEVIS_CLIENTS> LIGNES_CUISINE_DEVIS_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_CUISINE_FACTURE_CLIENTS> LIGNES_CUISINE_FACTURE_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_DEVIS_CLIENTS> LIGNES_DEVIS_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_DEVIS_FOURNISSEURS> LIGNES_DEVIS_FOURNISSEURS { get; set; }
        public virtual DbSet<LIGNES_FACTURES_CLIENTS> LIGNES_FACTURES_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_FACTURES_FOURNISSEURS> LIGNES_FACTURES_FOURNISSEURS { get; set; }
        public virtual DbSet<lIGNES_SERVICES> lIGNES_SERVICES { get; set; }
        public virtual DbSet<lIGNES_SERVICES_FACTURES> lIGNES_SERVICES_FACTURES { get; set; }
        public virtual DbSet<lIGNES_SERVICESSSTRAITANCE> lIGNES_SERVICESSSTRAITANCE { get; set; }
        public virtual DbSet<lIGNES_SERVICESSSTRAITANCE_FACTURE> lIGNES_SERVICESSSTRAITANCE_FACTURE { get; set; }
        public virtual DbSet<Links> Links { get; set; }
        public virtual DbSet<Marque> Marque { get; set; }
        public virtual DbSet<MOUVEMENETS_PRODUITS> MOUVEMENETS_PRODUITS { get; set; }
        public virtual DbSet<Parametrages> Parametrages { get; set; }
        public virtual DbSet<ParametrageSemaines> ParametrageSemaines { get; set; }
        public virtual DbSet<PERSONNEL_SOCIETE> PERSONNEL_SOCIETE { get; set; }
        public virtual DbSet<Personnels> Personnels { get; set; }
        public virtual DbSet<PrefixeTable> PrefixeTable { get; set; }
        public virtual DbSet<Prix_Achat> Prix_Achat { get; set; }
        public virtual DbSet<PRODUITS> PRODUITS { get; set; }
        public virtual DbSet<PROJET_TECHNIQUE> PROJET_TECHNIQUE { get; set; }
        public virtual DbSet<Projets> Projets { get; set; }
        public virtual DbSet<ProjetTechniques> ProjetTechniques { get; set; }
        public virtual DbSet<RASHonoraire> RASHonoraire { get; set; }
        public virtual DbSet<RASLoyer> RASLoyer { get; set; }
        public virtual DbSet<RASSalaire> RASSalaire { get; set; }
        public virtual DbSet<Rayons> Rayons { get; set; }
        public virtual DbSet<RETENUE_S_FOURNISSEURS> RETENUE_S_FOURNISSEURS { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<ROLE_PERSONNEL> ROLE_PERSONNEL { get; set; }
        public virtual DbSet<SERVICES> SERVICES { get; set; }
        public virtual DbSet<Societe_Centre_Couts> Societe_Centre_Couts { get; set; }
        public virtual DbSet<SocieteLogo> SocieteLogo { get; set; }
        public virtual DbSet<Societes> Societes { get; set; }
        public virtual DbSet<Sous_Categorie> Sous_Categorie { get; set; }
        public virtual DbSet<SOUS_TRAITANCE> SOUS_TRAITANCE { get; set; }
        public virtual DbSet<SS_FACADE> SS_FACADE { get; set; }
        public virtual DbSet<STATUE_CHEQUE> STATUE_CHEQUE { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tableau_Horaire> Tableau_Horaire { get; set; }
        public virtual DbSet<TABLES_BD> TABLES_BD { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TFP> TFP { get; set; }
        public virtual DbSet<Tiers> Tiers { get; set; }
        public virtual DbSet<Tracabilite_bl_Client> Tracabilite_bl_Client { get; set; }
        public virtual DbSet<Tracabilite_BL_Fournisseur> Tracabilite_BL_Fournisseur { get; set; }
        public virtual DbSet<Tracabilite_Caisse_Client> Tracabilite_Caisse_Client { get; set; }
        public virtual DbSet<Tracabilite_Commande_Client> Tracabilite_Commande_Client { get; set; }
        public virtual DbSet<Tracabilite_Commande_Fournisseur> Tracabilite_Commande_Fournisseur { get; set; }
        public virtual DbSet<Tracabilite_Devis_Client> Tracabilite_Devis_Client { get; set; }
        public virtual DbSet<Tracabilite_Devis_Fournisseur> Tracabilite_Devis_Fournisseur { get; set; }
        public virtual DbSet<Tracabilite_Facture_Client> Tracabilite_Facture_Client { get; set; }
        public virtual DbSet<Tracabilite_Facture_Fournisseur> Tracabilite_Facture_Fournisseur { get; set; }
        public virtual DbSet<TVA> TVA { get; set; }
        public virtual DbSet<TYPE_CAISSON> TYPE_CAISSON { get; set; }
        public virtual DbSet<TYPE_FACADE> TYPE_FACADE { get; set; }
        public virtual DbSet<Unite> Unite { get; set; }
        public virtual DbSet<ACTIVITE> ACTIVITE { get; set; }
        public virtual DbSet<BUDGETS> BUDGETS { get; set; }
        public virtual DbSet<Categorie_Sous_Categorie> Categorie_Sous_Categorie { get; set; }
        public virtual DbSet<PRINT_AVOIR_CLIENTS> PRINT_AVOIR_CLIENTS { get; set; }
        public virtual DbSet<PRINT_BON_LIVRAISON> PRINT_BON_LIVRAISON { get; set; }
        public virtual DbSet<PRINT_BON_LIVRAISON_PAR> PRINT_BON_LIVRAISON_PAR { get; set; }
        public virtual DbSet<PRINT_BonReception_Fournisseur> PRINT_BonReception_Fournisseur { get; set; }
        public virtual DbSet<PRINT_COMMANDE_CLIENT> PRINT_COMMANDE_CLIENT { get; set; }
        public virtual DbSet<PRINT_COMMANDES_FOURNISSEURS> PRINT_COMMANDES_FOURNISSEURS { get; set; }
        public virtual DbSet<PRINT_DEVIS_CLIENT> PRINT_DEVIS_CLIENT { get; set; }
        public virtual DbSet<PRINT_FACTURE_CLIENTS> PRINT_FACTURE_CLIENTS { get; set; }
        public virtual DbSet<PRINT_FACTURE_FOURNISSEUR> PRINT_FACTURE_FOURNISSEUR { get; set; }
        public virtual DbSet<PRINT_LISE_AVOIRS_CLIENTS> PRINT_LISE_AVOIRS_CLIENTS { get; set; }
        public virtual DbSet<PRINT_LISE_BON_LIVRAISONS> PRINT_LISE_BON_LIVRAISONS { get; set; }
        public virtual DbSet<PRINT_LISE_COMMANDES_CLIENTS> PRINT_LISE_COMMANDES_CLIENTS { get; set; }
        public virtual DbSet<PRINT_LISE_DEVIS_CLIENTS> PRINT_LISE_DEVIS_CLIENTS { get; set; }
        public virtual DbSet<PRINT_LISE_FACTURE_CLIENTS> PRINT_LISE_FACTURE_CLIENTS { get; set; }
        public virtual DbSet<PRINT_LISTE_BR> PRINT_LISTE_BR { get; set; }
        public virtual DbSet<PRINT_LISTE_DEVIS_FOURNISSEURS> PRINT_LISTE_DEVIS_FOURNISSEURS { get; set; }
        public virtual DbSet<PRINT_LISTE_FACTURE_FOURNISSEUR> PRINT_LISTE_FACTURE_FOURNISSEUR { get; set; }
        public virtual DbSet<PRINT_RETENUE> PRINT_RETENUE { get; set; }
        public virtual DbSet<LIGNES_DESCRIPTION_ACCESOIRE> LIGNES_DESCRIPTION_ACCESOIRE { get; set; }
        public virtual DbSet<LIGNES_DESCRIPTION_ACCESOIRE_BL> LIGNES_DESCRIPTION_ACCESOIRE_BL { get; set; }
        public virtual DbSet<LIGNES_DESCRIPTION_ACCESOIRE_CMD> LIGNES_DESCRIPTION_ACCESOIRE_CMD { get; set; }
        public virtual DbSet<LIGNES_DESCRIPTION_ACCESOIRE_Facture> LIGNES_DESCRIPTION_ACCESOIRE_Facture { get; set; }
        public virtual DbSet<LIGNES_DESCRIPTION_ACCESOIRE_CAISSE> LIGNES_DESCRIPTION_ACCESOIRE_CAISSE { get; set; }
        public virtual DbSet<LIGNES_CUISINE_AVOIR_CLIENTS> LIGNES_CUISINE_AVOIR_CLIENTS { get; set; }
        public virtual DbSet<LIGNES_DESCRIPTION_ACCESOIRE_AVOIR> LIGNES_DESCRIPTION_ACCESOIRE_AVOIR { get; set; }
        public virtual DbSet<lIGNE_SERVICE_FOURNISSEUR> lIGNE_SERVICE_FOURNISSEUR { get; set; }
        public virtual DbSet<FOURNISSEURS_TIERS> FOURNISSEURS_TIERS { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
