//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUVEMENETS_PRODUITS
    {
        public int ID { get; set; }
        public System.DateTime DATE_MOUVEMENT { get; set; }
        public string TYPE_MOUVEMENT { get; set; }
        public string CODE_MOUVEMENT { get; set; }
        public int QUANTITE_MOUVEMENT { get; set; }
        public int QUANTITE_AVANT_MOUVEMENT { get; set; }
        public int QUANTITE_APRES_MOUVEMENT { get; set; }
        public Nullable<int> Prix_achat { get; set; }
    
        public virtual Prix_Achat Prix_Achat1 { get; set; }
    }
}
