//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrageSemaines
    {
        public int Id { get; set; }
        public Nullable<int> JourId { get; set; }
        public string JourLibelle { get; set; }
        public Nullable<bool> jourTravail { get; set; }
        public Nullable<bool> doubleSeance { get; set; }
        public string seance1Debut { get; set; }
        public string seance1Fin { get; set; }
        public string seance2Debut { get; set; }
        public string seance2Fin { get; set; }
        public Nullable<int> projetTechniqueID { get; set; }
        public Nullable<System.DateTime> Date_Deb { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
        public string Date_FinString { get; set; }
        public string Date_DebString { get; set; }
    }
}
