//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnels()
        {
            this.AffaireCommerciales = new HashSet<AffaireCommerciales>();
            this.AffaireCommerciales1 = new HashSet<AffaireCommerciales>();
            this.AffaireCommerciales2 = new HashSet<AffaireCommerciales>();
            this.AffaireCommerciales3 = new HashSet<AffaireCommerciales>();
            this.COMMANDES_FOURNISSEURS = new HashSet<COMMANDES_FOURNISSEURS>();
            this.COMMANDES_FOURNISSEURS1 = new HashSet<COMMANDES_FOURNISSEURS>();
            this.lIGNES_SERVICES = new HashSet<lIGNES_SERVICES>();
            this.lIGNES_SERVICES_FACTURES = new HashSet<lIGNES_SERVICES_FACTURES>();
            this.PROJET_TECHNIQUE = new HashSet<PROJET_TECHNIQUE>();
            this.PROJET_TECHNIQUE1 = new HashSet<PROJET_TECHNIQUE>();
            this.PROJET_TECHNIQUE2 = new HashSet<PROJET_TECHNIQUE>();
            this.PROJET_TECHNIQUE3 = new HashSet<PROJET_TECHNIQUE>();
        }
    
        public int PersonnelId { get; set; }
        public string Nom { get; set; }
        public string Role { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public long Tel { get; set; }
        public Nullable<double> Cout_hor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffaireCommerciales> AffaireCommerciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffaireCommerciales> AffaireCommerciales1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffaireCommerciales> AffaireCommerciales2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AffaireCommerciales> AffaireCommerciales3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDES_FOURNISSEURS> COMMANDES_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDES_FOURNISSEURS> COMMANDES_FOURNISSEURS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICES> lIGNES_SERVICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICES_FACTURES> lIGNES_SERVICES_FACTURES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJET_TECHNIQUE> PROJET_TECHNIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJET_TECHNIQUE> PROJET_TECHNIQUE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJET_TECHNIQUE> PROJET_TECHNIQUE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJET_TECHNIQUE> PROJET_TECHNIQUE3 { get; set; }
    }
}
