//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrefixeTable
    {
        public Nullable<int> Id_Table { get; set; }
        public Nullable<int> Id_Ste { get; set; }
        public string Prefixe { get; set; }
        public int Id { get; set; }
    }
}
