//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINT_LISTE_DEVIS_FOURNISSEURS
    {
        public string Designation { get; set; }
        public int Product_ID { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> QUANTITE { get; set; }
        public string Libelle_Prd { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public string Expr1 { get; set; }
        public string CODE { get; set; }
        public int FOURNISSEUR { get; set; }
        public Nullable<decimal> THT { get; set; }
        public Nullable<decimal> NHT { get; set; }
        public Nullable<decimal> TTVA { get; set; }
        public decimal TTC { get; set; }
        public Nullable<decimal> TNET { get; set; }
        public int Societes { get; set; }
        public Nullable<double> PU_HT_Sans_Remise { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public Nullable<int> QUANTITE_REPTURE_STOCK { get; set; }
        public Nullable<double> PU_TTC { get; set; }
        public string Marque { get; set; }
        public Nullable<int> Categorie { get; set; }
        public Nullable<int> Sous_Categorie { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
