//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINT_BON_LIVRAISON
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int Societes { get; set; }
        public Nullable<int> Tiers { get; set; }
        public int Prix_achat { get; set; }
        public string DESIGNATION_PRODUIT { get; set; }
        public Nullable<double> QUANTITE { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string Expr3 { get; set; }
        public string ADRESSE { get; set; }
        public string MAIL { get; set; }
        public string RC { get; set; }
        public string NIS { get; set; }
        public string SITE_WEB { get; set; }
        public int Product_ID { get; set; }
        public int Expr4 { get; set; }
        public string ID_FISCAL { get; set; }
        public string AI { get; set; }
        public string Expr5 { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> Année { get; set; }
        public Nullable<int> SCoorID { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public int DiretionID { get; set; }
        public int Expr7 { get; set; }
        public string Expr8 { get; set; }
        public string NOM { get; set; }
        public string Expr9 { get; set; }
        public string TELEPHONE { get; set; }
        public string Expr10 { get; set; }
        public string EMAIL { get; set; }
        public string Expr11 { get; set; }
        public string Expr12 { get; set; }
        public string Expr13 { get; set; }
        public string Expr14 { get; set; }
        public string Expr15 { get; set; }
        public string RIB { get; set; }
        public string CONTACT { get; set; }
        public bool Exttva { get; set; }
        public int SociID { get; set; }
        public string Expr16 { get; set; }
        public string CODE_ACCES { get; set; }
        public Nullable<int> TiersID { get; set; }
        public Nullable<int> CentreID { get; set; }
        public Nullable<decimal> Capitale { get; set; }
        public Nullable<int> FRSID { get; set; }
        public string Direction { get; set; }
        public Nullable<int> Expr17 { get; set; }
        public string Expr18 { get; set; }
        public decimal TTC { get; set; }
        public Nullable<decimal> TTVA { get; set; }
        public Nullable<decimal> THT { get; set; }
        public Nullable<decimal> TOTALE_HT { get; set; }
        public Nullable<int> TVA { get; set; }
        public Nullable<decimal> TOTALE_TTC { get; set; }
        public Nullable<decimal> PRIX_UNITAIRE_HT { get; set; }
        public string Unite { get; set; }
        public string Libelle_Prd { get; set; }
        public string Expr19 { get; set; }
        public string Expr20 { get; set; }
        public string Expr21 { get; set; }
        public string MF { get; set; }
        public Nullable<int> Expr22 { get; set; }
    }
}
