//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINT_BON_LIVRAISON_PAR
    {
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int Societes { get; set; }
        public Nullable<int> Tiers { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> IDBLC { get; set; }
        public Nullable<int> Code_Article { get; set; }
        public string DESIGNATION_PRODUIT { get; set; }
        public Nullable<int> QTELIV { get; set; }
        public Nullable<int> QTERES { get; set; }
        public System.DateTime Expr2 { get; set; }
        public string Designation { get; set; }
        public string Nom { get; set; }
        public int DiretionID { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string Expr3 { get; set; }
        public string ADRESSE { get; set; }
        public string MAIL { get; set; }
        public string SITE_WEB { get; set; }
        public string ID_FISCAL { get; set; }
        public int SociID { get; set; }
        public string Expr4 { get; set; }
        public string CODE_ACCES { get; set; }
        public Nullable<int> TiersID { get; set; }
        public Nullable<int> CentreID { get; set; }
        public Nullable<decimal> Capitale { get; set; }
        public Nullable<int> FRSID { get; set; }
        public string Direction { get; set; }
        public string Email { get; set; }
    }
}
