//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prix_Achat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prix_Achat()
        {
            this.Art_Depot = new HashSet<Art_Depot>();
            this.Détails_Articles = new HashSet<Détails_Articles>();
            this.LIGNES_AVOIRS_CLIENTS = new HashSet<LIGNES_AVOIRS_CLIENTS>();
            this.LIGNES_AVOIRS_FOURNISSEURS = new HashSet<LIGNES_AVOIRS_FOURNISSEURS>();
            this.LIGNES_BONS_RECEPTIONS_FOURNISSEURS = new HashSet<LIGNES_BONS_RECEPTIONS_FOURNISSEURS>();
            this.LIGNES_Caisse = new HashSet<LIGNES_Caisse>();
            this.LIGNES_CUISINE_BONLIVRAISON_CLIENTS = new HashSet<LIGNES_CUISINE_BONLIVRAISON_CLIENTS>();
            this.LIGNES_CUISINE_CAISSE_CLIENTS = new HashSet<LIGNES_CUISINE_CAISSE_CLIENTS>();
            this.LIGNES_CUISINE_COMMANDE_CLIENTS = new HashSet<LIGNES_CUISINE_COMMANDE_CLIENTS>();
            this.LIGNES_CUISINE_DEVIS_CLIENTS = new HashSet<LIGNES_CUISINE_DEVIS_CLIENTS>();
            this.LIGNES_CUISINE_FACTURE_CLIENTS = new HashSet<LIGNES_CUISINE_FACTURE_CLIENTS>();
            this.LIGNES_FACTURES_CLIENTS = new HashSet<LIGNES_FACTURES_CLIENTS>();
            this.LIGNES_FACTURES_FOURNISSEURS = new HashSet<LIGNES_FACTURES_FOURNISSEURS>();
            this.MOUVEMENETS_PRODUITS = new HashSet<MOUVEMENETS_PRODUITS>();
        }
    
        public int Product_ID { get; set; }
        public string Designation { get; set; }
        public string Marque { get; set; }
        public Nullable<int> Categorie { get; set; }
        public Nullable<int> Sous_Categorie { get; set; }
        public string Unite { get; set; }
        public Nullable<double> PU_HT_Sans_Remise { get; set; }
        public Nullable<int> Remise { get; set; }
        public Nullable<double> PU_HT_Avec_Remise { get; set; }
        public string Devise { get; set; }
        public string Valeur_TVA { get; set; }
        public Nullable<double> PU_TTC { get; set; }
        public Nullable<int> Fournisseur { get; set; }
        public Nullable<System.DateTime> Date_offre_de_prix { get; set; }
        public Nullable<int> Duree_de_validite { get; set; }
        public string N_Offre_de_Prix { get; set; }
        public Nullable<double> QUANTITE { get; set; }
        public Nullable<int> QUANTITE_REPTURE_STOCK { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> BLfRS { get; set; }
        public Nullable<double> Stock { get; set; }
        public Nullable<double> Stock_Alerte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Art_Depot> Art_Depot { get; set; }
        public virtual Categorie Categorie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Détails_Articles> Détails_Articles { get; set; }
        public virtual Devise Devise1 { get; set; }
        public virtual FOURNISSEURS FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_AVOIRS_CLIENTS> LIGNES_AVOIRS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_AVOIRS_FOURNISSEURS> LIGNES_AVOIRS_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_BONS_RECEPTIONS_FOURNISSEURS> LIGNES_BONS_RECEPTIONS_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_Caisse> LIGNES_Caisse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_BONLIVRAISON_CLIENTS> LIGNES_CUISINE_BONLIVRAISON_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_CAISSE_CLIENTS> LIGNES_CUISINE_CAISSE_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_COMMANDE_CLIENTS> LIGNES_CUISINE_COMMANDE_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_DEVIS_CLIENTS> LIGNES_CUISINE_DEVIS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_CUISINE_FACTURE_CLIENTS> LIGNES_CUISINE_FACTURE_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_FACTURES_CLIENTS> LIGNES_FACTURES_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNES_FACTURES_FOURNISSEURS> LIGNES_FACTURES_FOURNISSEURS { get; set; }
        public virtual Marque Marque1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOUVEMENETS_PRODUITS> MOUVEMENETS_PRODUITS { get; set; }
        public virtual Sous_Categorie Sous_Categorie1 { get; set; }
        public virtual TVA TVA { get; set; }
        public virtual Unite Unite1 { get; set; }
    }
}
