//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUITS
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<int> FAMILLE { get; set; }
        public Nullable<bool> BLOQUE { get; set; }
        public string CODE_A_BARE { get; set; }
        public Nullable<decimal> PRIX_ACHAT_HT { get; set; }
        public Nullable<decimal> PRIX_VENTE_HT { get; set; }
        public Nullable<bool> AVEC_TVA { get; set; }
        public Nullable<int> TVA { get; set; }
        public Nullable<decimal> PRIX_VENTE_TTC { get; set; }
        public Nullable<int> QUANTITE { get; set; }
        public Nullable<int> QUANTITE_REPTURE_STOCK { get; set; }
        public string OBSERVATIONS { get; set; }
    }
}
