//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJET_TECHNIQUE
    {
        public int ProjetTechniqueId { get; set; }
        public string Reference { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public decimal Cout { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> PersonnelId { get; set; }
        public string EnCourExecution { get; set; }
        public string AffaireObtenue { get; set; }
        public Nullable<int> ResponsableTechnique { get; set; }
        public Nullable<int> CoordinateurCommerciale { get; set; }
        public Nullable<int> CoordinateurRealisation { get; set; }
        public Nullable<System.DateTime> DateLivraison { get; set; }
        public Nullable<System.DateTime> Delai_de_Soumission { get; set; }
        public Nullable<System.DateTime> Date_de_Soumission { get; set; }
        public Nullable<int> Id_AffaireCommerciale { get; set; }
    
        public virtual AffaireCommerciales AffaireCommerciales { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual Personnels Personnels { get; set; }
        public virtual Personnels Personnels1 { get; set; }
        public virtual Personnels Personnels2 { get; set; }
        public virtual Personnels Personnels3 { get; set; }
    }
}
