//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetTechniques
    {
        public int ProjetTechniqueId { get; set; }
        public string ReferenceTech { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public float Cout { get; set; }
        public int ClientId { get; set; }
        public int PersonnelId { get; set; }
        public string Statut { get; set; }
        public string Designation { get; set; }
        public float CoutReel { get; set; }
        public System.DateTime DateDebutReel { get; set; }
        public System.DateTime DateFinReel { get; set; }
        public Nullable<int> Devis_clt { get; set; }
        public Nullable<int> AffaireCommerciale { get; set; }
    }
}
