//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projets()
        {
            this.Decaissement = new HashSet<Decaissement>();
            this.Facturation = new HashSet<Facturation>();
        }
    
        public int PrID { get; set; }
        public string CODE { get; set; }
        public string NOM_PROJET { get; set; }
        public string TYPE { get; set; }
        public System.DateTime DEBUT { get; set; }
        public System.DateTime FIN { get; set; }
        public decimal MONTANT_HT { get; set; }
        public int TVA { get; set; }
        public decimal GARANTIE { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public int SociID { get; set; }
        public Nullable<int> DecaissID { get; set; }
        public Nullable<int> TiersID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decaissement> Decaissement { get; set; }
        public virtual Decaissement Decaissement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturation> Facturation { get; set; }
        public virtual Tiers Tiers { get; set; }
    }
}
