//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETENUE_S_FOURNISSEURS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RETENUE_S_FOURNISSEURS()
        {
            this.FACTURES_FOURNISSEURS = new HashSet<FACTURES_FOURNISSEURS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_FACT { get; set; }
        public Nullable<decimal> Montant_Brut { get; set; }
        public Nullable<decimal> Taux_Retenue { get; set; }
        public Nullable<decimal> Retenue { get; set; }
        public Nullable<decimal> Montant_net { get; set; }
        public Nullable<System.DateTime> Date_Retenue { get; set; }
        public Nullable<bool> Declaration { get; set; }
        public Nullable<System.DateTime> Date_Declaration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURES_FOURNISSEURS> FACTURES_FOURNISSEURS { get; set; }
        public virtual FACTURES_FOURNISSEURS FACTURES_FOURNISSEURS1 { get; set; }
    }
}
