//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICES()
        {
            this.lIGNES_SERVICES = new HashSet<lIGNES_SERVICES>();
            this.lIGNES_SERVICES_FACTURES = new HashSet<lIGNES_SERVICES_FACTURES>();
            this.lIGNES_SERVICESSSTRAITANCE = new HashSet<lIGNES_SERVICESSSTRAITANCE>();
            this.lIGNES_SERVICESSSTRAITANCE_FACTURE = new HashSet<lIGNES_SERVICESSSTRAITANCE_FACTURE>();
        }
    
        public int ID { get; set; }
        public string REF { get; set; }
        public string DES_SERVICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICES> lIGNES_SERVICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICES_FACTURES> lIGNES_SERVICES_FACTURES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICESSSTRAITANCE> lIGNES_SERVICESSSTRAITANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lIGNES_SERVICESSSTRAITANCE_FACTURE> lIGNES_SERVICESSSTRAITANCE_FACTURE { get; set; }
    }
}
