//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Societes()
        {
            this.AVOIRS_CLIENTS = new HashSet<AVOIRS_CLIENTS>();
            this.AVOIRS_FOURNISSEURS = new HashSet<AVOIRS_FOURNISSEURS>();
            this.Caisse = new HashSet<Caisse>();
            this.Direction1 = new HashSet<Direction>();
            this.Societe_Centre_Couts = new HashSet<Societe_Centre_Couts>();
            this.Tiers = new HashSet<Tiers>();
            this.Tiers1 = new HashSet<Tiers>();
        }
    
        public int SociID { get; set; }
        public string NOM { get; set; }
        public string CODE_ACCES { get; set; }
        public Nullable<int> TiersID { get; set; }
        public Nullable<int> CentreID { get; set; }
        public Nullable<decimal> Capitale { get; set; }
        public Nullable<int> FRSID { get; set; }
        public string Direction { get; set; }
        public Nullable<int> SCoorID { get; set; }
        public string Email { get; set; }
        public string Utilisateur { get; set; }
        public byte[] logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVOIRS_CLIENTS> AVOIRS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVOIRS_FOURNISSEURS> AVOIRS_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caisse> Caisse { get; set; }
        public virtual CoordonneesSoc CoordonneesSoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direction> Direction1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Societe_Centre_Couts> Societe_Centre_Couts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tiers> Tiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tiers> Tiers1 { get; set; }
    }
}
