//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
	using System.Web;

	public partial class SocieteLogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SocieteLogo()
        {
            this.BONS_LIVRAISONS_CLIENTS = new HashSet<BONS_LIVRAISONS_CLIENTS>();
            this.BONS_RECEPTIONS_FOURNISSEURS = new HashSet<BONS_RECEPTIONS_FOURNISSEURS>();
            this.CLIENTS = new HashSet<CLIENTS>();
            this.COMMANDES_CLIENTS = new HashSet<COMMANDES_CLIENTS>();
            this.COMMANDES_FOURNISSEURS = new HashSet<COMMANDES_FOURNISSEURS>();
            this.DEVIS_CLIENTS = new HashSet<DEVIS_CLIENTS>();
            this.DEVIS_FOURNISSEURS = new HashSet<DEVIS_FOURNISSEURS>();
            this.Direction = new HashSet<Direction>();
            this.FACTURES_CLIENTS = new HashSet<FACTURES_CLIENTS>();
            this.FACTURES_FOURNISSEURS = new HashSet<FACTURES_FOURNISSEURS>();
            this.FOURNISSEURS = new HashSet<FOURNISSEURS>();
            this.Caisse = new HashSet<Caisse>();
            this.AVOIRS_CLIENTS = new HashSet<AVOIRS_CLIENTS>();
        }
    
        public string Nom_Societe { get; set; }
        public string logo { get; set; }
        public int id { get; set; }
        public string Adresse { get; set; }
        public string mail { get; set; }
        public string RC { get; set; }
        public string MF { get; set; }
        public Nullable<int> Tel { get; set; }
        public string IBAN { get; set; }
        public string RIB { get; set; }
        public string Agence { get; set; }
        public string Web { get; set; }
        public string Capitale { get; set; }
		public HttpPostedFileBase file { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONS_LIVRAISONS_CLIENTS> BONS_LIVRAISONS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONS_RECEPTIONS_FOURNISSEURS> BONS_RECEPTIONS_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTS> CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDES_CLIENTS> COMMANDES_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDES_FOURNISSEURS> COMMANDES_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVIS_CLIENTS> DEVIS_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVIS_FOURNISSEURS> DEVIS_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direction> Direction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURES_CLIENTS> FACTURES_CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURES_FOURNISSEURS> FACTURES_FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOURNISSEURS> FOURNISSEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caisse> Caisse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVOIRS_CLIENTS> AVOIRS_CLIENTS { get; set; }
    }
}
