//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tableau_Horaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tableau_Horaire()
        {
            this.Horaire1 = new HashSet<Horaire>();
        }
    
        public string Nom { get; set; }
        public Nullable<System.DateTime> Date_Deb { get; set; }
        public int id { get; set; }
        public Nullable<int> jour { get; set; }
        public Nullable<int> Horaire { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horaire> Horaire1 { get; set; }
        public virtual Horaire Horaire2 { get; set; }
        public virtual Jours Jours { get; set; }
    }
}
