//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.Links = new HashSet<Links>();
            this.Links1 = new HashSet<Links>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal Progress { get; set; }
        public int SortOrder { get; set; }
        public string Type { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> ProjetTechniquesID { get; set; }
        public Nullable<int> owner_id { get; set; }
        public System.DateTime planned_start { get; set; }
        public System.DateTime planned_end { get; set; }
        public string color { get; set; }
        public int duration_h { get; set; }
        public int Duration { get; set; }
        public Nullable<int> duration_planning { get; set; }
        public Nullable<int> duration_h_planning { get; set; }
        public System.DateTime EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Links> Links { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Links> Links1 { get; set; }
    }
}
