//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tiers()
        {
            this.Projets = new HashSet<Projets>();
            this.Societes1 = new HashSet<Societes>();
        }
    
        public int TiersID { get; set; }
        public int SociID { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string NOM { get; set; }
        public string ADRESSE { get; set; }
        public string MAIL { get; set; }
        public string SITE_WEB { get; set; }
        public string ID_FISCAL { get; set; }
        public string AI { get; set; }
        public string NIS { get; set; }
        public string RC { get; set; }
        public string RIB { get; set; }
        public Nullable<int> Clt { get; set; }
        public Nullable<int> frs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projets> Projets { get; set; }
        public virtual Societes Societes { get; set; }
        public virtual Tiers Tiers1 { get; set; }
        public virtual Tiers Tiers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Societes> Societes1 { get; set; }
    }
}
