//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracabilite_Devis_Client
    {
        public int ID { get; set; }
        public Nullable<bool> Ajoute_Par { get; set; }
        public Nullable<bool> Modifie_Par { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Societe { get; set; }
        public Nullable<int> Id_Devis { get; set; }
        public Nullable<int> Id_ligne_Devis { get; set; }
        public Nullable<int> Personnel { get; set; }
    }
}
